spring:
  profiles:
    active: local
  datasource:
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://203.170.59.95:3306/jmang?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
   username: root
   password: 123456wind
  jackson:
    default-property-inclusion: non_null
  resources:
    add-mappings: false
  http:
    multipart:
     enable: true
     max-file-size: 50MB
     max-request-size: 50MB
server:
  tomcat:
    accept-count: 10000
    threads:
      max: 500
    uri-encoding: UTF-8
    accesslog:
      enabled: true
      pattern: "%h %l &u %t \"%r\ %s %b %D"
      directory: ${APP_HOME}/logs
    remoteip:
      port-header:
mybatis-plus:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
logging:
  config: classpath:logback-spring.xml
swagger:
  enable: true
---
spring:
    profiles: local
server:
    port: 10210
